# Generated by Django 2.2.5 on 2019-10-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_of_groups',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_transactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_privacy',
            field=models.CharField(choices=[('private', 'private'), ('public', 'public'), ('friends', 'friends')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('casual', 'casual'), ('silver', 'silver'), ('gold', 'gold'), ('platinum', 'platinum'), ('commercial', 'commercial')], default='casual', max_length=20),
        ),
    ]
