# Generated by Django 2.2.5 on 2019-10-28 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Constraint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_constraint', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
