# Generated by Django 2.1.5 on 2019-10-30 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Constraint', '0002_auto_20191028_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_constraint', to=settings.AUTH_USER_MODEL),
        ),
    ]
