# Generated by Django 2.2.5 on 2019-10-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='otp',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.IntegerField(default=-1),
        ),
    ]
