# Generated by Django 2.1.5 on 2019-10-29 23:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0003_auto_20191030_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
