# Generated by Django 2.1.5 on 2019-10-30 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0004_otp_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='date_posted',
        ),
    ]
