# Generated by Django 2.1.5 on 2019-10-30 04:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0005_remove_otp_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
