# Generated by Django 2.1.5 on 2019-10-31 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0006_otp_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_money_transaction',
            name='amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
