# Generated by Django 2.2.5 on 2019-10-23 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('date_posted', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('group_name', models.TextField(max_length=100, unique=True)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=100)),
                ('date_posted', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups.Group')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group_join_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups.Group')),
                ('user_requesting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_join_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
