# Generated by Django 2.2.5 on 2019-10-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='user_privacy',
            field=models.CharField(choices=[('private', 'private'), ('public', 'public'), ('friends', 'friends')], default='public', max_length=20),
        ),
    ]
