# Generated by Django 2.2.5 on 2019-10-21 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='message',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
