# Generated by Django 2.2.5 on 2019-10-29 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0002_auto_20191028_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='cost',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='group',
            name='user_privacy',
            field=models.CharField(choices=[('private', 'private'), ('public', 'public')], default='public', max_length=20),
        ),
    ]
