# Generated by Django 2.2.5 on 2019-10-21 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Groups', '0003_auto_20191022_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='message',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='group',
            name='sender',
        ),
        migrations.CreateModel(
            name='group_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups.Group')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
