# Generated by Django 2.2.5 on 2019-10-22 00:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0004_auto_20191022_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_post',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
