# Generated by Django 2.2.5 on 2019-10-22 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Groups', '0005_group_post_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_join_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups.Group')),
                ('user_requesting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_join_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
